studios = Studio.create([
    {name: 'Millennium Dance Complex', website: 'http://millenniumdancecomplex.com'},
    {name: 'Movement Lifestyle', website: 'https://www.themovementlifestyle.com'},
    {name: 'The Playground LA', website: 'https://www.playgroundla.dance'}
])

addresses = Address.create([
  {line_1: '11528 Ventura Blvd,', line_2: 'Studio City, CA 91604', studio_id: Studio.find_by(name: 'Millennium Dance Complex').id},
  {line_1: '11105 Weddington St,', line_2: 'North Hollywood, CA 91601', studio_id: Studio.find_by(name: 'Movement Lifestyle').id},
  {line_1: '7375 Melrose Ave,', line_2: 'Los Angeles, CA 90046', studio_id: Studio.find_by(name: 'The Playground LA').id}
])

instructors = Instructor.create([
  {name: 'Margie Dilivio', video_url: 'https://youtu.be/RMXR_YmhmMs'},
  {name: 'Nick Gilligan', video_url: 'https://youtu.be/TxZahWlyGnE'},
  {name: 'Charlie Bartley', video_url: 'https://youtu.be/WPkhMuLQJ94'},
  {name: 'Kennis Marquis', video_url: 'https://youtu.be/bJs7D6rlYc4'},
  {name: 'Nicole Kirkland', video_url: 'https://youtu.be/hBBaKsOW32w'},
  {name: 'Sam Allen', video_url: 'https://youtu.be/WQXjeIkgXJg'},
  {name: 'Ava Bernstine-Mitchell', video_url: 'https://youtu.be/1NsLltabXvI'},
  {name: 'Dexter Carr', video_url: 'https://youtu.be/wO7RzMKFg0g'},
  {name: 'Michelle Janine', video_url: 'https://youtu.be/1-WuQF3r4rY'},
  {name: 'Marissa Heart', video_url: 'https://youtu.be/pUb8Pc1zY-k'},
  {name: 'Julian Deguzman', video_url: 'https://youtu.be/i5UuLF61juc'},
  {name: 'Phil Wright', video_url: 'https://youtu.be/MXOzcXTJ5DA'},
  {name: 'Rex Kline', video_url: 'https://youtu.be/3j0nuqrREek'},
  {name: 'Shane Bruce', video_url: 'https://youtu.be/48cbutOLhRU'},
  {name: 'Hamilton Evans', video_url: 'https://youtu.be/RToQkzRAp1Q'},
  {name: 'Kenny Wormald', video_url: 'https://youtu.be/taJx2AhYqvc'},
  {name: 'Alexis Beauregard', video_url: 'https://youtu.be/_1OjIchrIEQ'},
  {name: 'Brinn Nicole', video_url: 'https://youtu.be/LSTWxbQFanE'},
  {name: 'Cisco Ruelas', video_url: 'https://youtu.be/lPJfTbQ7bDg'},
  {name: 'JJ Dancer', video_url: 'https://youtu.be/ByqO-y85HWA'},
  {name: 'Guy Groove', video_url: 'https://youtu.be/9dWTMmILb7c'},
  {name: 'Rumer Noel', video_url: 'https://youtu.be/t9ZUghgWWF4'},
  {name: 'A\'Drey Vinogradov', video_url: 'https://youtu.be/LF49YENK8Rw'},
  {name: 'Alec Clawson', video_url: 'https://youtu.be/K4wVL3ho1nI'},
  {name: 'Alex Fetbroth', video_url: 'https://youtu.be/cH-3tzDTKFE'},
  {name: 'Alexander Chung', video_url: 'https://youtu.be/epX-ocXmFZk'},
  {name: "Anthony 'Kanec' Carr", video_url: 'https://youtu.be/f8nGj9oJeF0'},
  {name: 'Antoine Troupe', video_url: 'https://youtu.be/y47AsHaKYbU'},
  {name: 'Anze Skrube', video_url: 'https://youtu.be/d4mp3w8WqXY'},
  {name: 'Bobby Dacones', video_url: 'https://youtu.be/XPLhhANYeDE'},
  {name: 'Brian and Scott Nicholson', video_url: 'https://youtu.be/vcLWIOzQBeI'},
  {name: 'Brooklyn Jai', video_url: 'https://youtu.be/cSg7UiJVUzE'},
  {name: 'Bryan Tanaka', video_url: 'https://youtu.be/mWAAFlPQcqM'},
  {name: 'Cameron Lee', video_url: 'https://youtu.be/FXWkLAHfniU'},
  {name: 'Candace Brown', video_url: 'https://youtu.be/Wx8A2-Sbf9M'},
  {name: 'CJ Salvador', video_url: 'https://youtu.be/N0sQuby82D8'},
  {name: 'Coby Mosby', video_url: 'https://youtu.be/xPxvTsSgGds'},
  {name: 'Dae Dae Coleman', video_url: 'https://youtu.be/juMJlf1b75Q'},
  {name: 'Dana Alexa', video_url: 'https://youtu.be/ugSR7E8QJAU'},
  {name: 'Dana Wilson', video_url: 'https://youtu.be/9SScW-88svU'},
  {name: 'Dasha Tertova', video_url: 'https://youtu.be/BI6nvGOGkm4'},
  {name: 'David Moore', video_url: 'https://youtu.be/asMz0viwSjs'},
  {name: 'Devin Solomon', video_url: 'https://youtu.be/f2wHl9Pgy6Y'},
  {name: 'Dez Soliven', video_url: 'https://youtu.be/bPpum3uveUk'},
  {name: 'Donyelle Jones', video_url: 'https://youtu.be/2ARY7WsktF4'},
  {name: 'Eddie Morales', video_url: 'https://youtu.be/QQEJV-uEVPw'},
  {name: 'Eric Ellis', video_url: 'https://youtu.be/WRycLb88jSo'},
  {name: 'Erica Klein', video_url: 'https://youtu.be/3AqCMUvb0jI'},
  {name: 'J Smooth', video_url: 'https://youtu.be/9KhmpGPMgIM'},
  {name: 'Janelle Ginestra', video_url: 'https://youtu.be/YkgszNzgrQ8'},
  {name: 'Jasmine Rafael', video_url: 'https://youtu.be/yJSab3-xS-g'},
  {name: 'Jeff Victor', video_url: 'https://youtu.be/G4Ui9mEgh_U'},
  {name: 'Jeremiah Haynes', video_url: 'https://youtu.be/rEZsXMLTCxc'},
  {name: "Jose 'Boy Boi' Tena", video_url: 'https://youtu.be/vwRQzVq99dM'},
  {name: 'Josh Williams', video_url: 'https://youtu.be/BjjUZPbiMx8'},
  {name: 'JR Taylor', video_url: 'https://youtu.be/SYDg0MzGacQ'},
  {name: 'Karon Lynn', video_url: 'https://youtu.be/zdERZ3SppKk'},
  {name: 'Kayla Janssen', video_url: 'https://youtu.be/DXx7t59eIKs'},
  {name: 'Kenya Clay', video_url: 'https://youtu.be/qU7sLx5o3Lg'},
  {name: 'King Guttah', video_url: 'https://youtu.be/EPjUcLtLAhI'},
  {name: 'King Kai', video_url: 'https://youtu.be/-2CarFf4cqE'},
  {name: 'Lando Coffy', video_url: 'https://youtu.be/Ns2nE8oDx18'},
  {name: 'Laura Quinn', video_url: 'https://youtu.be/g8_UKOHv_EM'},
  {name: 'Lindsay Taylor', video_url: 'https://youtu.be/UpVy-hHUFPw'},
  {name: 'Luam', video_url: 'https://youtu.be/-oY30Lp8FqU'},
  {name: 'Marie Poppins', video_url: 'https://youtu.be/FTfzDBAbsrc'},
  {name: 'Matt Steffanina', video_url: 'https://youtu.be/HZRMonTRP30'},
  {name: 'Misha Gabriel', video_url: 'https://youtu.be/mpvZjtVm_eQ'},
  {name: 'Molle Gray', video_url: 'https://youtu.be/fG73ThgWlyw'},
  {name: 'Mykell Wilson', video_url: 'https://youtu.be/8DbAPyqm5MQ'},
  {name: 'Natalie Gilmore', video_url: 'https://youtu.be/kCTaVPTXrBg'},
  {name: 'Nathan Trasoras', video_url: ''},
  {name: 'Nick Demoura', video_url: ''},
  {name: 'Nick Lanzisera', video_url: ''},
  {name: 'Nicky T', video_url: ''},
  {name: 'Nico O\'Connor', video_url: ''},
  {name: 'Nika', video_url: ''},
  {name: 'Noah Tratree', video_url: ''},
  {name: 'Pete Styles', video_url: ''},
  {name: 'Phil Wright', video_url: ''},
  {name: 'Regina Williams', video_url: ''},
  {name: 'Rudy Abreu', video_url: ''},
  {name: 'Shockwave', video_url: ''},
  {name: 'Stefanie Santiago', video_url: ''},
  {name: 'Tasha Hamilton', video_url: ''},
  {name: 'Todd Flanagan', video_url: ''},
  {name: 'Tokyo', video_url: ''},
  {name: 'Trey Rich', video_url: ''},
  {name: 'Tricia Miranda', video_url: ''},
  {name: 'Will Bell', video_url: ''},
  {name: 'Willdabeast Adams', video_url: ''},
  {name: 'Zach Lattimore', video_url: ''}
])

dance_classes = DanceClass.create([
  #regular schedule from The Playground LA
  {name: 'Booty Bake', studio_id: Studio.find_by(name: 'The Playground LA').id, instructor_id: Instructor.find_by(name: 'Margie Dilivio').id, day: 'MONDAY',time: '9:15am-10:15am'},
  {name: 'Hip Hope', studio_id: Studio.find_by(name: 'The Playground LA').id, instructor_id: Instructor.find_by(name: 'Nick Gilligan').id, day: 'MONDAY',time: '4:30pm-5:30pm'},
  {name: 'Hip Hop', studio_id: Studio.find_by(name: 'The Playground LA').id, instructor_id: Instructor.find_by(name: 'Charlie Bartley').id, day: 'MONDAY',time: '5:30pm-7:00pm'},
  {name: 'Grooves', studio_id: Studio.find_by(name: 'The Playground LA').id, instructor_id: Instructor.find_by(name: 'Kennis Marquis').id, day: 'MONDAY',time: '7:00pm-8:15pm'},
  {name: 'Heels', studio_id: Studio.find_by(name: 'The Playground LA').id, instructor_id: Instructor.find_by(name: 'Nicole Kirkland').id, day: 'MONDAY',time: '8:30pm-10:00pm'},
  {name: 'Hip Hop', studio_id: Studio.find_by(name: 'The Playground LA').id, instructor_id: Instructor.find_by(name: 'Sam Allen').id, day: 'TUESDAY',time: '5:30pm-6:30pm'},
  {name: 'Hip Hop', studio_id: Studio.find_by(name: 'The Playground LA').id, instructor_id: Instructor.find_by(name: 'Ava Bernstine-Mitchell').id, day: 'TUESDAY',time: '7:00pm-8:15pm'},
  {name: 'Hip Hop', studio_id: Studio.find_by(name: 'The Playground LA').id, instructor_id: Instructor.find_by(name: 'Dexter Carr').id, day: 'TUESDAY',time: '8:30pm-10:00pm'},
  {name: 'Booty Bake', studio_id: Studio.find_by(name: 'The Playground LA').id, instructor_id: Instructor.find_by(name: 'Michelle Janine').id, day: 'WEDNESDAY',time: '9:15am-10:15am'},
  {name: 'Hip Hop', studio_id: Studio.find_by(name: 'The Playground LA').id, instructor_id: Instructor.find_by(name: 'Nick Gilligan').id, day: 'WEDNESDAY',time: '10:30am-11:45am'},
  {name: 'Heels', studio_id: Studio.find_by(name: 'The Playground LA').id, instructor_id: Instructor.find_by(name: 'Marissa Heart').id, day: 'WEDNESDAY',time: '5:00pm-6:30pm'},
  {name: 'Hip Hop', studio_id: Studio.find_by(name: 'The Playground LA').id, instructor_id: Instructor.find_by(name: 'Julian Deguzman').id, day: 'WEDNESDAY',time: '6:30pm-8:00pm'},
  {name: 'Hip Hop', studio_id: Studio.find_by(name: 'The Playground LA').id, instructor_id: Instructor.find_by(name: 'Nicole Kirkland').id, day: 'WEDNESDAY',time: '8:00pm-9:30pm'},
  {name: 'Hip Hop', studio_id: Studio.find_by(name: 'The Playground LA').id, instructor_id: Instructor.find_by(name: 'Phil Wright').id, day: 'WEDNESDAY',time: '9:30pm-11:00pm'},
  {name: 'Contemporary', studio_id: Studio.find_by(name: 'The Playground LA').id, instructor_id: Instructor.find_by(name: 'Rex Kline').id, day: 'THURSDAY',time: '2:00pm-3:30pm'},
  {name: 'Hip Hop', studio_id: Studio.find_by(name: 'The Playground LA').id, instructor_id: Instructor.find_by(name: 'Shane Bruce').id, day: 'THURSDAY',time: '5:00pm-6:00pm'},
  {name: 'Hip Hop', studio_id: Studio.find_by(name: 'The Playground LA').id, instructor_id: Instructor.find_by(name: 'Hamilton Evans').id, day: 'THURSDAY',time: '6:30pm-7:45pm'},
  {name: 'Hip Hop', studio_id: Studio.find_by(name: 'The Playground LA').id, instructor_id: Instructor.find_by(name: 'Kenny Wormald').id, day: 'THURSDAY',time: '8:00pm-9:30pm'},
  {name: 'Beginner Heels', studio_id: Studio.find_by(name: 'The Playground LA').id, instructor_id: Instructor.find_by(name: 'Alexis Beauregard').id, day: 'FRIDAY',time: '5:00pm-6:00pm'},
  {name: 'Heels', studio_id: Studio.find_by(name: 'The Playground LA').id, instructor_id: Instructor.find_by(name: 'Brinn Nicole').id, day: 'FRIDAY',time: '6:00pm-8:00pm'},
  {name: 'Heels', studio_id: Studio.find_by(name: 'The Playground LA').id, instructor_id: Instructor.find_by(name: 'Cisco Ruelas').id, day: 'FRIDAY',time: '8:30pm-10:00pm'},
  {name: 'Bangin Body', studio_id: Studio.find_by(name: 'The Playground LA').id, instructor_id: Instructor.find_by(name: 'JJ Dancer').id, day: 'SATURDAY',time: '10:30am-11:30am'},
  {name: 'Hip Hop', studio_id: Studio.find_by(name: 'The Playground LA').id, instructor_id: Instructor.find_by(name: 'Charlie Bartley').id, day: 'SATURDAY', time: '12:00pm-1:15pm'},
  {name: 'Beginner Heels', studio_id: Studio.find_by(name: 'The Playground LA').id, instructor_id: Instructor.find_by(name: 'Alexis Beauregard').id, day: 'SATURDAY',time: '1:30pm-2:45pm'},
  {name: 'Hip Hop', studio_id: Studio.find_by(name: 'The Playground LA').id, instructor_id: Instructor.find_by(name: 'Dexter Carr').id, day: 'SATURDAY',time: '3:00pm-4:30pm'},
  {name: 'Hip Hop', studio_id: Studio.find_by(name: 'The Playground LA').id, instructor_id: Instructor.find_by(name: 'Guy Groove').id, day: 'SUNDAY',time: '1200pm-1:00pm'},
  {name: 'Jazz Funk', studio_id: Studio.find_by(name: 'The Playground LA').id, instructor_id: Instructor.find_by(name: 'Rumer Noel').id, day: 'SUNDAY',time: '1:00pm-2:15pm'}
  #regular schedule from Movement Lifestyle
  #{name: '', studio_id: Studio.find_by(name: 'The Movement Lifestyle').id, instructor_id: #Instructor.find_by(name: '').id, day: 'SATURDAY',time: ''}
])
